swagger: '2.0'
info:
  title: Cities API
  description: API used to ingest data from the Chicago Taxi Tripsdatabase and independent
    sources
  version: v1
basePath: /
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /chicago_dataset_ingest:
    post:
      operationId: chicago_dataset_ingest_create
      description: |-
        Query the public dataset, and upload retrieved data to the data
        warehouse on BigQuery
      parameters: []
      responses:
        '204':
          description: Succesfully uploaded data
      tags:
        - chicago_dataset_ingest
    parameters: []
  /private_source_ingest:
    post:
      operationId: private_source_ingest_create
      description: |-
        Parse the uploaded CSV file, retrieve the location fix of the
        coordinates and upload the results to the data warehouse in BigQuery
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/PrivateSourceIngest'
      responses:
        '204':
          description: Succesfully uploaded data
      tags:
        - private_source_ingest
    parameters: []
definitions:
  PrivateSourceIngest:
    type: object
    properties:
      data_file:
        title: Data file
        type: string
        readOnly: true
        format: uri
